version: "3"
services:
  cassandra:
    image: "cassandra:3.11"
    hostname: "cassandra"
    container_name: "cassandra"
    ports:
      - "7000:7000"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - "${PWD}/cassandra_vol:/ddl"
  elasticsearch:
    image: "elasticsearch:6.6.2"
    hostname: "elasticsearch"
    container_name: elasticsearch
    stdin_open: true
    tty: true
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
  kibana:
    image: "kibana:6.6.2"
    hostname: "kibana"
    container_name: "kibana"
    ports:
      - "5601:5601"
    links:
      - "elasticsearch:elasticsearch"
  logstash:
    image: "logstash:6.6.2"
    hostname: "logstash"
    container_name: "logstash"
    stdin_open: true
    tty: true
    volumes:
      - "${PWD}/logstash_vol:/config-dir"
    links:
      - "cassandra:cassandra"
      - "elasticsearch:elasticsearch"